// vue-app/src/App.vue
<template>
  <HelloWorld :reactCounter="reactCounter"/>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data() {
    return {
      websocket: null,
      reactCounter: '0'
    };
  },
  created() {
    console.log('Vue: Estableciendo conexión WebSocket...');
    this.websocket = new WebSocket('ws://localhost:9001');

    this.websocket.onopen = () => {
      console.log('Vue: WebSocket connection established');
    };

    this.websocket.onmessage = (event) => {
      console.log('Vue: Received message:', event.data);
      this.reactCounter = JSON.parse(event.data)?.counterUpdate;
    };

    this.websocket.onerror = (error) => {
      console.error('Vue: WebSocket error:', error);
    };

    this.websocket.onclose = () => {
      console.log('Vue: WebSocket connection closed');
    };
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// angular-app/angularApp/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
  title = 'angularApp';
  reactCounter: string; // Inicializamos el contador con '0'
  websocket: WebSocket;

  constructor() {
    this.reactCounter = "0";
    this.websocket = new WebSocket('ws://localhost:9001'); // Inicializamos websocket en el constructor
  }

  ngOnInit() {
    this.websocket.onopen = () => {
      console.log('Angular: WebSocket connection established');
    };

    this.websocket.onmessage = (event) => {
      console.log('Angular: Received message:', event.data);
      this.reactCounter = JSON.parse(event.data)?.counterUpdate;
    };

    this.websocket.onerror = (error) => {
      console.error('Angular: WebSocket error:', error);
    };

    this.websocket.onclose = () => {
      console.log('Angular: WebSocket connection closed');
    };
  }
}

<style>
  #root {
    background-color: red;
  }

  h1 {
    margin: 0
  }
</style>

<div id="root">
  <h1>Contenido hecho en Angular. Contador de React: {{ reactCounter }}</h1>
</div>

<router-outlet></router-outlet>
